- name: Check Raspberry Pi Temperature
  hosts: all
  gather_facts: false

  tasks:
  - name: Measure temperature
    ansible.builtin.command: "vcgencmd measure_temp"
    register: _temperature
    changed_when: false

  - name: Show temperature
    ansible.builtin.debug:
      var: _temperature['stdout']
